[package]
name = "wasm"
version = "0.1.0"
edition = "2021"
authors = ["k-kuroguro"]
license = "MIT"

[liba]
crate-type = ["cdylib"]

[dependencies]
image = "0.23.7"
qrcode = "0.12.0"

js-sys = "0.3.66"
web-sys = "0.3.66"

wasm-bindgen = "0.2.89"
